name: CI

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.3

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./pkg/metal/...
